CREATE TABLE IF NOT EXISTS VEHICLE360_DB.PUBLIC.AGENT_THREADS (
  THREAD_ID STRING PRIMARY KEY,
  USER_NAME STRING,
  CREATED_AT TIMESTAMP_TZ,
  TITLE STRING
);

CREATE TABLE IF NOT EXISTS VEHICLE360_DB.PUBLIC.AGENT_MESSAGES (
  THREAD_ID STRING,
  MESSAGE_ID NUMBER,
  ROLE STRING,
  CONTENT STRING,
  CREATED_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS VEHICLE360_DB.PUBLIC.API_CALL_AUDIT (
  START_TS TIMESTAMP_TZ,
  END_TS   TIMESTAMP_TZ,
  THREAD_ID STRING,
  PARENT_MESSAGE_ID NUMBER,
  PROMPT STRING,
  HTTP_STATUS NUMBER
);
